CC = gcc

all: 1P1CLR 1PNCLR 1PNCLRS 1PNCBR 1PNCBRS

1P1CLR: 1P1CLR.c
	$(CC) -o $@ $< -lpthread

1PNCLR: 1PNCLR.c
	$(CC) -o $@ $< -lpthread

1PNCLRS: 1PNCLRS.c
	$(CC) -o $@ $< -lpthread

1PNCBR: 1PNCBR.c
	$(CC) -o $@ $< -lpthread

1PNCBRS: 1PNCBRS.c
	$(CC) -o $@ $< -lpthread

clean :
	rm -f 1P1CLR 1PNCLR 1PNCLRS 1PNCBR 1PNCBRS 
